name: Deploy SimpleBank

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  REGION: us-east-2
  VERSION: v1

  ECR: 489741402840.dkr.ecr.us-east-2.amazonaws.com
  IMAGE: 489741402840.dkr.ecr.us-east-2.amazonaws.com/2-tier-deployment

  S3_BUCKET: s3://489741402840-devops-scripts

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: Abhisheksharma2022-del/2-Tier-Deployment
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::489741402840:role/GitHub-OIDC-Role
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          set -e

          aws ecr get-login-password \
          --region ${{ env.REGION }} \
          | docker login \
          --username AWS \
          --password-stdin \
          ${{ env.ECR }}

      - name: Build Docker Image
        run: |
          set -e

          docker build \
          -t ${{ env.IMAGE }}:${{ env.VERSION }} .

      - name: Push Docker Image
        run: |
          set -e

          docker push \
          ${{ env.IMAGE }}:${{ env.VERSION }}

      - name: Upload docker-compose.yml to S3
        run: |
          set -e

          aws s3 cp \
          docker-compose.yml \
          ${{ env.S3_BUCKET }}/docker-compose.yml \
          --region ${{ env.REGION }}

      - name: Deploy on EC2 using SSM
        id: deploy

        run: |

          CMD_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:App,Values=flask" \
            --region ${{ env.REGION }} \
            --comment "Deploy Version ${{ env.VERSION }}" \
            --parameters '{
              "commands":[
                "set -e",
                "mkdir -p /home/ubuntu/app",

                "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 489741402840.dkr.ecr.us-east-2.amazonaws.com",

                "aws s3 cp s3://489741402840-devops-scripts/docker-compose.yml /home/ubuntu/app/docker-compose.yml",

                "docker pull 489741402840.dkr.ecr.us-east-2.amazonaws.com/2-tier-deployment:v1",

                "docker stop simplebank || true",

                "docker rm simplebank || true",

                "cd /home/ubuntu/app",

                "IMAGE_TAG=v1 docker compose up -d",

                "docker ps"
              ]
            }' \
            --query "Command.CommandId" \
            --output text)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Wait for Deployment
        run: |

          for i in {1..12}
          do

            STATUS=$(aws ssm list-command-invocations \
              --command-id "${{ steps.deploy.outputs.cmd_id }}" \
              --query "CommandInvocations[*].Status" \
              --output text \
              --region ${{ env.REGION }})

            echo "Attempt $i : $STATUS"

            if [[ "$STATUS" == "Pending" || "$STATUS" == "InProgress" ]]; then
              sleep 10
            else
              break
            fi

          done

      - name: Deployment Result
        run: |

          aws ssm list-command-invocations \
          --command-id "${{ steps.deploy.outputs.cmd_id }}" \
          --details \
          --region ${{ env.REGION }}

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.deploy.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region ${{ env.REGION }})

          if [ "$FAILED" -gt 0 ]; then
            echo "Deployment Failed"
            exit 1
          fi

          echo "Deployment Successful"